# before running compose you will need to run
# docker network create assistnet
# docker volume create mongo-data
# docker volume create postgres-data
# and 
# export PASSWORD=some_password

assistant:
  image: duanenielsen/assistant
  container_name: assistant
  net: "assistnet"
  ports:
   - "8080:8080"
  environment:
   - "POSTGRES_ENV_POSTGRES_PASSWORD=${PASSWORD}"
mongo:
  image: mongo:2.6.11
  container_name: mongo
  net: "assistnet"
  volumes:
   - mongo-data:/data/db
postgres:
  image: postgres:9.3.10
  container_name: postgres
  net: "assistnet"
  ports:
   - "5432:5432"
  environment:
   - "POSTGRES_PASSWORD=${PASSWORD}"
  volumes:
   - postgres-data:/var/lib/postgresql/data
